
### signup
POST http://localhost:8888/auth/signup
Content-Type: application/json

{
  "firstName": "Vamsi",
  "lastName": "Digamarthi",
  "email": "vamsi2@test.com",
  "mobile": "9876543210",
  "password": "mypassword"
}

### login
POST http://localhost:8888/auth/login
Content-Type: application/json

{
  "email": "vamsi@test.com",
  "password": "mypassword"
}